const ICON_MAP: { match: string; icon: string }[] = [
  { match: "laravel", icon: "bi-boxes" },
  { match: "php", icon: "bi-filetype-php" },
  { match: "python", icon: "bi-filetype-py" },
  { match: "fastapi", icon: "bi-lightning-charge-fill" },
  { match: "django", icon: "bi-braces" },
  { match: "node", icon: "bi-filetype-node" },
  { match: "express", icon: "bi-shield" },
  { match: "rest", icon: "bi-diagram-3" },
  { match: "graphql", icon: "bi-box" },
  { match: "mysql", icon: "bi-database-fill" },
  { match: "postgres", icon: "bi-database" },
  { match: "sqlite", icon: "bi-database-dash" },
  { match: "mongodb", icon: "bi-database-fill-add" },
  { match: "redis", icon: "bi-database-fill-gear" },
  { match: "firebase", icon: "bi-fire" },
  { match: "supabase", icon: "bi-cloud-arrow-up-fill" },
  { match: "html", icon: "bi-filetype-html" },
  { match: "css", icon: "bi-filetype-css" },
  { match: "sass", icon: "bi-filetype-scss" },
  { match: "tailwind", icon: "bi-wind" },
  { match: "javascript", icon: "bi-filetype-js" },
  { match: "typescript", icon: "bi-filetype-tsx" },
  { match: "jquery", icon: "bi-code-slash" },
  { match: "bootstrap", icon: "bi-bootstrap" },
  { match: "vue", icon: "bi-code-square" },
  { match: "react", icon: "bi-atom" },
  { match: "next", icon: "bi-box-seam" },
  { match: "angular", icon: "bi-hexagon" },
  { match: "svelte", icon: "bi-caret-right-square" },
  { match: "wordpress", icon: "bi-wordpress" },
  { match: "machine learning", icon: "bi-cpu-fill" },
  { match: "computer vision", icon: "bi-eye-fill" },
  { match: "deep learning", icon: "bi-hdd-network-fill" },
  { match: "neural", icon: "bi-bezier2" },
  { match: "cnn", icon: "bi-diagram-3-fill" },
  { match: "yolo", icon: "bi-bullseye" },
  { match: "transfer learning", icon: "bi-arrow-repeat" },
  { match: "grad-cam", icon: "bi-search" },
  { match: "nlp", icon: "bi-chat-square-text-fill" },
  { match: "automation", icon: "bi-robot" },
  { match: "llm", icon: "bi-cpu" },
  { match: "ai ", icon: "bi-cpu" },
  { match: "tensorflow", icon: "bi-cpu-fill" },
  { match: "pytorch", icon: "bi-graph-up-arrow" },
  { match: "pandas", icon: "bi-table" },
  { match: "opencv", icon: "bi-eye" },
  { match: "hugging", icon: "bi-emoji-smile" },
  { match: "git", icon: "bi-git" },
  { match: "github", icon: "bi-github" },
  { match: "gitlab", icon: "bi-gitlab" },
  { match: "docker", icon: "bi-box" },
  { match: "kubernetes", icon: "bi-grid-3x3-gap" },
  { match: "aws", icon: "bi-cloud" },
  { match: "azure", icon: "bi-cloud-fill" },
  { match: "gcp", icon: "bi-cloud-sun" },
  { match: "vercel", icon: "bi-triangle-fill" },
  { match: "cloudflare", icon: "bi-cloud-slash" },
  { match: "linux", icon: "bi-terminal" },
  { match: "bash", icon: "bi-terminal-fill" },
  { match: "excel", icon: "bi-table" },
  { match: "power bi", icon: "bi-bar-chart-fill" },
  { match: "figma", icon: "bi-bezier" },
  { match: "photoshop", icon: "bi-palette-fill" },
  { match: "postman", icon: "bi-box-arrow-up" },
  { match: "seo", icon: "bi-search-heart" },
  { match: "react native", icon: "bi-phone-fill" },
  { match: "flutter", icon: "bi-phone" },
  { match: "java", icon: "bi-cup-hot" },
  { match: "c#", icon: "bi-hash" },
  { match: "c++", icon: "bi-plus-slash-minus" },
  { match: "go", icon: "bi-arrow-up-right-circle" },
  { match: "rust", icon: "bi-shield-fill" },
  { match: "solidity", icon: "bi-coin" },
];

const FALLBACK_ICON = "bi-code-slash";

export function getSkillIcon(skillName: string, explicitIcon?: string): string {
  if (explicitIcon && explicitIcon.trim()) return explicitIcon.trim();
  const name = skillName.toLowerCase();
  for (const entry of ICON_MAP) {
    if (name.includes(entry.match)) return entry.icon;
  }
  return FALLBACK_ICON;
}