-- Convert generated-always identity columns to by-default so the seed script can insert explicit ids.
DO $body$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['social_links','nav_items','skill_categories','skills','services','portfolio_categories','portfolio_items','education','experience','messages']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', t);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', t);
  END LOOP;
END
$body$;