-- Individual skills table (per-skill CRUD).
-- Existing skill_categories.skills jsonb array is left in place for legacy
-- data but is no longer used by the app; add rows to public.skills instead.
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category_id bigint not null default 0,
  name text not null default '',
  icon text not null default '',
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.skills enable row level security;
create policy "public read skills" on public.skills for select to anon using (true);
