-- ============================================================
-- Hridoy Portfolio - Supabase schema
-- Run this in Supabase Dashboard -> SQL Editor -> New query
-- ============================================================

-- Storage bucket for public images
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

create policy "public read images"
  on storage.objects for select
  using (bucket_id = 'images');

-- Storage bucket for resume / CV files (pdf, doc, docx)
insert into storage.buckets (id, name, public,
  file_size_limit, allowed_mime_types)
values ('cv', 'cv', true, 10485760,
  array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']::text[])
on conflict (id) do nothing;

create policy "public read cv"
  on storage.objects for select
  using (bucket_id = 'cv');

-- ------------------------------------------------------------
-- profile (single row, id = 1)
-- ------------------------------------------------------------
create table if not exists public.profile (
  id bigint primary key default 1 check (id = 1),
  name text not null default '',
  role text not null default '',
  typed_items jsonb not null default '[]'::jsonb,
  subtitle text not null default '',
  cv_url text not null default '',
  email text not null default '',
  phone text not null default '',
  city text not null default '',
  degree text not null default '',
  availability text not null default '',
  github_handle text not null default '',
  github_url text not null default '',
  linkedin_handle text not null default '',
  linkedin_url text not null default '',
  photo_url text not null default '',
  hero_bg_url text not null default '',
  about_headline text not null default '',
  about_intro text not null default '',
  about_body jsonb not null default '[]'::jsonb,
  resume_summary text not null default '',
  resume_bullets jsonb not null default '[]'::jsonb,
  facts jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profile enable row level security;
create policy "public read profile" on public.profile for select to anon using (true);

-- ------------------------------------------------------------
-- social_links
-- ------------------------------------------------------------
create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  label text not null default '',
  icon text not null default '',
  url text not null default '',
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.social_links enable row level security;
create policy "public read social_links" on public.social_links for select to anon using (true);

-- ------------------------------------------------------------
-- nav_items
-- ------------------------------------------------------------
create table if not exists public.nav_items (
  id bigint generated by default as identity primary key,
  section_id text not null unique,
  label text not null default '',
  icon text not null default '',
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.nav_items enable row level security;
create policy "public read nav_items" on public.nav_items for select to anon using (true);

-- ------------------------------------------------------------
-- skill_categories (grouped skills, skills stored as jsonb list)
-- ------------------------------------------------------------
create table if not exists public.skill_categories (
  id bigint generated by default as identity primary key,
  label text not null default '',
  icon text not null default '',
  skills jsonb not null default '[]'::jsonb,
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.skill_categories enable row level security;
create policy "public read skill_categories" on public.skill_categories for select to anon using (true);

-- ------------------------------------------------------------
-- services
-- ------------------------------------------------------------
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  icon text not null default '',
  title text not null default '',
  description text not null default '',
  points jsonb not null default '[]'::jsonb,
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.services enable row level security;
create policy "public read services" on public.services for select to anon using (true);

-- ------------------------------------------------------------
-- portfolio_categories
-- ------------------------------------------------------------
create table if not exists public.portfolio_categories (
  id bigint generated by default as identity primary key,
  value text not null unique,
  label text not null default '',
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.portfolio_categories enable row level security;
create policy "public read portfolio_categories" on public.portfolio_categories for select to anon using (true);

-- ------------------------------------------------------------
-- portfolio_items
-- ------------------------------------------------------------
create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null default '',
  categories jsonb not null default '[]'::jsonb,
  description text not null default '',
  image text not null default '',
  screenshots jsonb not null default '[]'::jsonb,
  technologies jsonb not null default '[]'::jsonb,
  live_url text not null default '',
  github_url text not null default '',
  detail_category text not null default '',
  detail_client text not null default '',
  detail_date text not null default '',
  detail_status text not null default '',
  sections jsonb not null default '[]'::jsonb,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  position int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.portfolio_items enable row level security;
create policy "public read portfolio_items" on public.portfolio_items for select to anon using (true);

-- ------------------------------------------------------------
-- education
-- ------------------------------------------------------------
create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text not null default '',
  institution text not null default '',
  description text not null default '',
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.education enable row level security;
create policy "public read education" on public.education for select to anon using (true);

-- ------------------------------------------------------------
-- experience
-- ------------------------------------------------------------
create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  role text not null default '',
  organization text not null default '',
  period text not null default '',
  description text not null default '',
  responsibilities jsonb not null default '[]'::jsonb,
  position int not null default 0,
  is_published boolean not null default true
);

alter table public.experience enable row level security;
create policy "public read experience" on public.experience for select to anon using (true);

-- ------------------------------------------------------------
-- messages (contact form submissions)
-- ------------------------------------------------------------
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text not null default '',
  subject text not null default '',
  message text not null default '',
  is_read boolean not null default false,
  is_archived boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;
create policy "public insert messages" on public.messages for insert to anon with check (true);
create index if not exists messages_created_at_idx on public.messages (created_at desc);

-- ------------------------------------------------------------
-- theme (single row, id = 1)
-- ------------------------------------------------------------
create table if not exists public.theme (
  id bigint primary key default 1 check (id = 1),
  accent text not null default '#149ddd',
  accent_dark text not null default '#0f7fae',
  accent_soft text not null default '#d7eefb',
  navy text not null default '#040b14',
  navy_light text not null default '#151f2b',
  heading text not null default '#050d18',
  body text not null default '#272829',
  light text not null default '#f4fafd',
  navm text not null default '#a8a9b4',
  danger text not null default '#df1529',
  success text not null default '#059652',
  hero_overlay_opacity int not null default 30 check (hero_overlay_opacity between 0 and 100),
  font_heading text not null default 'raleway',
  font_body text not null default 'roboto',
  font_nav text not null default 'poppins',
  updated_at timestamptz not null default now()
);

alter table public.theme enable row level security;
create policy "public read theme" on public.theme for select to anon using (true);

-- ------------------------------------------------------------
-- settings (key -> jsonb value)
-- keys: meta, hero, footer, section_subtitles, resume_labels,
--       service_details, contact
-- ------------------------------------------------------------
create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.settings enable row level security;
create policy "public read settings" on public.settings for select to anon using (true);